### PR TITLE
Add some wasi-threads tests

### PR DESCRIPTION
**Pull request by yamt**
```
(venv) spacetanuki% TOYWASM=~/git/toywasm/b/toywasm python3 test-runner/wasi_test_runner.py -t tests/wat/testsuite -r ~/git/toywasm/test/wasi-testsuite-adapter.py
Test wasi_threads_exit_nonmain_wasi passed
Test wasi_threads_exit_main_busy passed
Test wasi_threads_exit_main_wasi passed
Test wasi_threads_exit_nonmain_busy passed
Test wasi_threads_spawn passed
Test wasi_threads_exit_main_block passed
Test wasi_threads_exit_nonmain_block passed

===== Test results =====
Runtime: toywasm v0.0
Suite: WASI wat tests
  Total: 7
  Passed:  7
  Failed:  0

Test suites: 1 passed, 0 total
Tests:       7 passed, 0 total
(venv) spacetanuki% 
```

### CODE REVIEW

**Comment by yamt** [comment]
i've written these while implementing wasi-threads in toywasm.
but nothing in these tests is toywasm-specific as far as i know.

**Comment by loganek** [comment]
I'll review the tests in details after end of year holidays, but my initial thought was that this should for now live in https://github.com/WebAssembly/wasi-threads? In fact there's one basic test added there already: https://github.com/WebAssembly/wasi-threads/pull/11

**Comment by yamt** [comment]
> I'll review the tests in details after end of year holidays, but my initial thought was that this should for now live in https://github.com/WebAssembly/wasi-threads? In fact there's one basic test added there already: [WebAssembly/wasi-threads#11](https://github.com/WebAssembly/wasi-threads/pull/11)

i haven't noticed that the "basic test" there was for the same test runner.
maybe i will move there.

**Comment by yamt** [comment]
moved to https://github.com/WebAssembly/wasi-threads/pull/19

**Pull request closed without merging**
