### PR TITLE
Add license file

### LINKED ISSUE #15: license
can you add a clear license info to this repo?

### PR DESCRIPTION
**Pull request by loganek**
Resolves #15

### CODE REVIEW

**Comment by loganek** [comment]
@sunfishcode @cimacmillan please have a look and approve if you agree.

**Review by yamt — COMMENTED** [review]
lgtm

**Comment by sunfishcode** [comment]
Apache-2.0 is the same as what most other WebAssembly repos use, so I assume that's ok.

However, for the NOTICE file, I don't know of any WebAssembly repositories that include a NOTICE file. I've sent a message to the CG chairs to see if they have any input here.

**Comment by loganek** [comment]
@sunfishcode do you have any update on that? Thanks

**Comment by sunfishcode** [comment]
I've not yet received a reply from the CG chairs.

**Comment by loganek** [comment]
I removed NOTICE file

**Pull request merged**
