### PR TITLE
Add an adapter for WAMR

### PR DESCRIPTION
**Pull request by yamt**
```
(venv) spacetanuki% python3 test-runner/wasi_test_runner.py -t tests/assemblyscript/testsuite tests/c/testsuite -r adapters/wasm-micro-runtime.sh
Test environ_get-multiple-variables passed
Test fd_write-to-invalid-fd passed
Test environ_sizes_get-multiple-variables passed
Test args_sizes_get-no-arguments passed
Test args_get-multiple-arguments passed
Test args_sizes_get-multiple-arguments passed
Test fd_write-to-stdout passed
Test random_get-non-zero-length passed
Test environ_sizes_get-no-variables passed
Test random_get-zero-length passed
Test clock_getres-realtime passed
Test clock_gettime-monotonic passed
Test clock_getres-monotonic passed
Test clock_gettime-realtime passed

===== Test results =====
Runtime: iwasm v1.0.0
Suite: WASI Assemblyscript tests
  Total: 10
  Passed:  10
  Failed:  0

Suite: WASI C tests
  Total: 4
  Passed:  4
  Failed:  0

Test suites: 2 passed, 0 total
Tests:       14 passed, 0 total
(venv) spacetanuki%
```

### CODE REVIEW

**Comment by loganek** [comment]
Hi @yamt, could you make a change in test so it's expected to fail? Tests are based on exit codes, IIRC WAMR didn't by default pass exit code from module to user through `iwasm`. Is there any build flag to enable this behavior? If so, probably worth adding a comment in the adapter.

**Comment by yamt** [comment]
> Hi @yamt, could you make a change in test so it's expected to fail? Tests are based on exit codes, IIRC WAMR didn't by default pass exit code from module to user through `iwasm`. Is there any build flag to enable this behavior? If so, probably worth adding a comment in the adapter.

iirc, wamr doesn't have a way to preserve wasi exit code.
probaby i will add it in upstream.

**Comment by yamt** [comment]
in the meantime i added a comment.

**Comment by yamt** [comment]
updated after https://github.com/bytecodealliance/wasm-micro-runtime/pull/1748

**Comment by yamt** [comment]
updated after fopen test

**Review by loganek — APPROVED** [review]

**Pull request merged**
